from enum import IntEnum, auto

# Lowest number is drawn in the front
class DrawOrder(IntEnum):
    FRONT = auto()
    MOUSE_SELECT_BOX = auto()
    SELECTOR_MENU_BUTTON = auto()
    SELECTOR_MENU_BACKGROUND = auto()
    TAB = auto()
    TAB_BACKGROUND = auto()
    UI_BUTTON = auto()
    SCROLLBAR_BORDER = auto()
    SCROLLBAR = auto()
    DROPDOWN_TEXT = auto()
    DROPDOWN_BACKGROUND = auto()
    GRADIENT_SEPARATOR = auto()
    COMMAND_INSERTER = auto()
    READOUT = auto()
    WIDGET = auto()
    COMMANND_BLOCK = auto()
    PANEL_BACKGROUND = auto()
    CONSTRAINT_LINES = auto()
    THETA_LINE = auto()
    THETA_NODE = auto()
    NODE = auto()
    SEGMENT = auto()
    BEFORE_NODE_SEGMENT = auto()
    MENU_LINE = auto()
    FIELD_BACKGROUND = auto()
    BACKGROUND = auto()
    BACK = auto()